#pragma config(Sensor, S1,     sideSensor,     sensorSONAR)
#pragma config(Sensor, S2,     frontSensor,    sensorSONAR)
#pragma config(Sensor, S3,     rightLightSensor, sensorLightActive)
#pragma config(Sensor, S4,     leftLightSensor, sensorLightActive)
#pragma config(Motor,  motorA,          leftmotor,     tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightmotor,    tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*  This program reads the light sensor and follow a line materialised by a black tape on a white floor   *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]               [Type]              [Description]                      *|
|*    Port A                  leftmotor              NXT                 Left motor                       *|
|*    Port B                  rightmotor             NXT                 Right motor                      *|
|*    Port 1                  sideSensor          Sonar Sensor           side facing                      *|
|*    Port 2                  frontSensor         Sonar Sensor           front facing                     *|
|*    Port 3                  rightLightSensor    Light Sensor           floor facing                     *|
|*    Port 4                  leftLightSensor     Light Sensor           floor facing                     *|
\*--------------------------------------------------------------------------------------------------------*/

// global variables
int sidedistance = 0;     // Will hold the values read in by the side Sonar Sensor.
int frontdistance = 0;     // Will hold the values read in by the front Sonar Sensor.
int leftlight = 0;     // Will hold the values read in by the left Light Sensor.
int rightlight = 0;     // Will hold the values read in by the right Light Sensor.
int lightthreshold = 36;          // Define the threshold between black and white colors (white ~ 50; black ~ 30)// (maze 1 = 36)
int sidethresh = 29;           // Define the threshold for detecting a wall
int frontthresh = 31;

void displaysensors() {
	displayCenteredTextLine(0, "side distance");       /* Display side Sonar Sensor values */
	displayCenteredTextLine(1, "%d", sidedistance);   /* to LCD screen using %d.     */
	displayCenteredTextLine(2, "front distance");       /* Display front Sonar Sensor values */
	displayCenteredTextLine(3, "%d", frontdistance);   /* to LCD screen using %d.     */
	displayCenteredTextLine(4, "left light");       /* Display left Light Sensor values */
	displayCenteredTextLine(5, "%d", leftlight);   /* to LCD screen using %d.     */
	displayCenteredTextLine(6, "right light");       /* Display right Light Sensor values */
	displayCenteredTextLine(7, "%d", rightlight);   /* to LCD screen using %d.     */
	//wait1Msec(100);                                       // Only update the screen every 100 milliseconds.
}

void readsensors()
{
	sidedistance =	SensorValue(sideSensor);               // Store side Sonar Sensor values in 'sonarValueSide' variable.
	frontdistance =	SensorValue(frontSensor);							// Store front Sonar Sensor values in 'sonarValueFront' variable.
	leftlight =			SensorValue(leftLightSensor);          // Store left Light Sensor values in 'lightValueLeft' variable.
	rightlight = 		SensorValue(rightLightSensor) - 8;				// Store right Light Sensor values in 'lightValueRight' variable and offset
	displaysensors();
}

void checkdirection()																	// Checking whether there are walls to the side and to the front
{
	readsensors();

	if (sidedistance > sidethresh && sidedistance != 255)             //if there is no wall to the left (hardcoded for 255 bug)
	{
		motor(leftmotor) = -7;																						// turn left
		motor(rightmotor) = 7;
		wait1Msec(2500);
		while (rightlight > lightthreshold) // while right is seeing white
		{
			readsensors();
			motor(leftmotor) = -7;																						// turn left
			motor(rightmotor) = 7;
		}
		motor(leftmotor) = 0;
		motor(rightmotor) = 0;
		wait1Msec(500);
	}

	else if ( frontdistance < frontthresh || frontdistance == 255)       // if there is a wall in front (hardcoded for 255 bug)
	{

		//motor(leftmotor) = -7;                  															// reverse for turning circle
		//motor(rightmotor) = -7;
		//wait1Msec(1000);

		//motor(leftmotor) = 0;																					//pause
		//motor(rightmotor) = 0;
		//wait1Msec(500);

		motor(leftmotor) = 7;																						// turn right
		motor(rightmotor) = -7;
		wait1Msec(2500);
		while (rightlight > lightthreshold) // while left is seeing white
		{
			readsensors();
			motor(leftmotor) = 7;																						// turn right
			motor(rightmotor) = -7;
		}
		motor(leftmotor) = 0;
		motor(rightmotor) = 0;
		wait1Msec(500);

		checkdirection();

	}
}

task main()																														// Line following function
{
	while(true)        // (infinite loop, also represented by 'while(1)).
	{
		readsensors();
		motor(leftmotor) = (leftlight - rightlight/2 - 2);
		motor(rightmotor) = (rightlight - leftlight/2 - 2);

		if ((leftlight < lightthreshold)&&(rightlight < lightthreshold))  // If the Light Sensor reads a value less than 45:
		{
			wait1Msec(1000);
			motor(leftmotor) = 0;                  															// leftmotor is run at a 0 power level.
			motor(rightmotor) = 0;                			 												// rightmotor is run at a 0 power level.
			wait1Msec(500);
			checkdirection();



		}
	}
}



// line following - offset light sensors
// perpendicularity
// front threshold?
